apiVersion: v1
kind: Service
metadata:
  labels:
    app: mystamps
  name: mystamps
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mystamps
  type: LoadBalancer
